
CREATE TABLE [dbo].[temporalsegmentoCAPISIG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPANIA] NVARCHAR(100) NULL,
	[SEGMENTO] NVARCHAR(100) NULL,
	[VALORPRIMATOTAL] [nvarchar](1000) NULL,
	[DESCRIPCION] [nvarchar](1000) NULL,
	[FECHACREACION] [datetime] NOT NULL,
 CONSTRAINT [PK_temporalsegmentOcapiSIG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[temporalsegmentoCAPISIG] ADD  
CONSTRAINT [DF_temporalsegmentoCAPISIG_FECHACREACION]  DEFAULT (getdate()) FOR [FECHACREACION]
GO


