CREATE TABLE [dbo].[NegociostempError] (
    [id]                        INT            IDENTITY (1, 1) NOT NULL,
    [compania_id]               NVARCHAR (250) NULL,
    [lineaNegocio_id]           NVARCHAR (250) NULL,
    [ramo_id]                   NVARCHAR (250) NULL,
    [amparo_id]                 NVARCHAR (250) NULL,
    [cobertura_id]              NVARCHAR (250) NULL,
    [modalidadPago_id]          NVARCHAR (250) NULL,
    [producto_id]               NVARCHAR (250) NULL,
    [plan_id]                   NVARCHAR (250) NULL,
    [numeroNegocio]             NVARCHAR (250) NULL,
    [fechaExpedicion]           NVARCHAR (250) NULL,
    [fechaCancelacion]          NVARCHAR (250) NULL,
    [fechaEmisionMaximoEndoso]  NVARCHAR (250) NULL,
    [fechaRecaudoInicial]       NVARCHAR (250) NULL,
    [formaPago_id]              NVARCHAR (250) NULL,
    [estadoNegocio_id]          NVARCHAR (250) NULL,
    [numeroSolicitud]           NVARCHAR (250) NULL,
    [cuotasVencidas]            NVARCHAR (250) NULL,
    [cuotasPagadas]             NVARCHAR (250) NULL,
    [valorAsegurado]            NVARCHAR (250) NULL,
    [valorProteccion]           NVARCHAR (250) NULL,
    [valorAhorro]               NVARCHAR (250) NULL,
    [valorPrimaPensiones]       NVARCHAR (250) NULL,
    [valorPrimaTotal]           NVARCHAR (250) NULL,
    [identificacionSuscriptor]  NVARCHAR (250) NULL,
    [nombreSuscriptor]          NVARCHAR (250) NULL,
    [fechaNacimientoSuscriptor] NVARCHAR (250) NULL,
    [actividadEconomica_id]     NVARCHAR (250) NULL,
    [generoSuscriptor]          NVARCHAR (250) NULL,
    [zona_id]                   NVARCHAR (250) NULL,
    [localidad_id]              NVARCHAR (250) NULL,
    [clave]                     NVARCHAR (250) NULL,
    [porcentajeParticipacion]   NVARCHAR (250) NULL,
    [grupoEndoso_id]            NVARCHAR (250) NULL,
    [tipoEndoso_id]             NVARCHAR (250) NULL,
    [codigoAgrupador]           NVARCHAR (250) NULL,
    [marcaVehiculo]             NVARCHAR (250) NULL,
    [tipoVehiculo]              NVARCHAR (250) NULL,
    [modeloVehiculo]            NVARCHAR (250) NULL,
    [sistema]                   NVARCHAR (250) NULL,
    [Usuarios]                  NVARCHAR (250) NULL,
    [ErrorCode]                 NVARCHAR (250) NULL,
    [ErrorColumnName]           NVARCHAR (250) NULL,
    [ErrorColumnCode]           NVARCHAR (250) NULL,
    [cliente_id]                NVARCHAR (250) NULL,
    [fechaGrabacion]            NVARCHAR (250) NULL,
    [estadoCierre]              INT            NULL,
    [mesCierre]                 INT            NULL,
    [anioCierre]                INT            NULL
);





