CREATE TABLE [dbo].[InformeFabrica] (
    [id]                    INT            IDENTITY (1, 1) NOT NULL,
    [zona_nombre]           NCHAR (200)    NULL,
    [localidad_id]          INT            NULL,
    [localidad_nombre]      NVARCHAR (200) NULL,
    [codigoNivel]           NVARCHAR (160) NULL,
    [director_nombre]       NVARCHAR (200) NULL,
    [clave]                 NVARCHAR (40)  NULL,
    [asesor_nombre]         NVARCHAR (401) NULL,
    [abreviatura]           NVARCHAR (100) NULL,
    [fechaIngreso]          DATETIME       NULL,
    [fechaRevivido]         DATETIME       NULL,
    [fechaRetiro]           DATETIME       NULL,
    [ingreso1]              FLOAT          NULL,
    [ingreso2]              FLOAT          NULL,
    [ingreso3]              FLOAT          NULL,
    [ingreso4]              FLOAT          NULL,
    [ingreso5]              FLOAT          NULL,
    [ingreso6]              FLOAT          NULL,
    [antiguedadAnterior]    FLOAT          NULL,
    [antiguedad]            FLOAT          NULL,
    [nombreCanal]           NVARCHAR (200) NULL,
    [grupoAnterior]         INT            NULL,
    [grupo]                 INT            NULL,
    [minimoExigidoAnterior] FLOAT          NULL,
    [minimoExigido]         FLOAT          NULL,
    [mesesMedidos]          INT            NULL,
    [ingresoSegunMes]       FLOAT          NULL,
    [promedioIngreso]       FLOAT          NULL,
    [ingresosExigidos]      FLOAT          NULL,
    [porceCumplimientoIng]  FLOAT          NULL,
    [cumplenIngresos]       NVARCHAR (10)  NULL,
    [porceCumplimientoCol]  FLOAT          NULL,
    [ingresoSum]            TINYINT        NULL,
    [coltitulos]            NVARCHAR (10)  NULL,
    [pos]                   NVARCHAR (2)   NULL,
    [mesesMedidosProy]      INT            NULL,
    [ingresoSegunMesProy]   FLOAT          NULL,
    [proyIngresosExigidos]  FLOAT          NULL,
    [proyIngresosProxMes]   FLOAT          NULL
);

