/*CREATE TABLE [dbo].[Negociostemp] (
    [id]                        INT            IDENTITY (1, 1) NOT NULL,
    [compania_id]               NVARCHAR (50)  NULL,
    [lineaNegocio_id]           NVARCHAR (50)  NULL,
    [ramo_id]                   NVARCHAR (50)  NULL,
    [amparo_id]                 NVARCHAR (50)  NULL,
    [cobertura_id]              NVARCHAR (50)  NULL,
    [modalidadPago_id]          NVARCHAR (50)  NULL,
    [productoCodigo]            NVARCHAR (50)  NULL,
    [plan_id]                   NVARCHAR (50)  NULL,
    [numeroNegocio]             NVARCHAR (50)  NULL,
    [fechaExpedicion]           NVARCHAR (50)  NULL,
    [fechaCancelacion]          NVARCHAR (50)  NULL,
    [fechaEmisionMaximoEndoso]  NVARCHAR (50)  NULL,
    [fechaRecaudoInicial]       NVARCHAR (50)  NULL,
    [formaPago_id]              INT            NULL,
    [cuotasVencidas]            NVARCHAR (50)  NULL,
    [cuotasPagadas]             NVARCHAR (50)  NULL,
    [valorAsegurado]            NVARCHAR (50)  NULL,
    [valorProteccion]           NVARCHAR (50)  NULL,
    [valorAhorro]               NVARCHAR (50)  NULL,
    [valorPrimaPensiones]       NVARCHAR (50)  NULL,
    [valorPrimaTotal]           NVARCHAR (50)  NULL,
    [nombreSuscriptor]          NVARCHAR (250) NULL,
    [fechaNacimientoSuscriptor] NVARCHAR (50)  NULL,
    [actividadEconomica_id]     NVARCHAR (50)  NULL,
    [generoSuscriptor]          NVARCHAR (50)  NULL,
    [zona_id]                   INT            NULL,
    [localidad_id]              INT            NULL,
    [clave]                     NVARCHAR (250) NULL,
    [porcentajeParticipacion]   NVARCHAR (250) NULL,
    [grupoEndoso_id]            NVARCHAR (50)  NULL,
    [tipoEndoso_id]             NVARCHAR (50)  NULL,
    [marcaVehiculo]             NVARCHAR (50)  NULL,
    [tipoVehiculo]              NVARCHAR (50)  NULL,
    [modeloVehiculo]            NVARCHAR (50)  NULL,
    [sistema]                   NVARCHAR (50)  NULL,
    [Usuarios]                  INT            NULL,
    [codigoAgrupador]           NVARCHAR (50)  NULL,
    [estado]                    NVARCHAR (50)  NULL,
    [numeroSolicitud]           NVARCHAR (50)  NULL,
    [identificacionSuscriptor]  NVARCHAR (250) NULL,
    [cliente_id]                INT            NULL,
    [participante_id]           INT            NULL,
    [tipoDocumento_id]          NVARCHAR (50)  NULL,
    [fechaGrabacion]            NVARCHAR (50)  NULL,
    [estadoCierre]              INT            NULL,
    [mesCierre]                 INT            NULL,
    [anioCierre]                INT            NULL
);*/







