CREATE TABLE [dbo].[Comisiontemp] (
    [codigoAgrupacion]          NVARCHAR (50) NULL,
    [codigoEmpresa]             NVARCHAR (50) NULL,
    [codigoEmpresaNovedad]      NVARCHAR (50) NULL,
    [codigoProductor]           NVARCHAR (50) NULL,
    [claveAsesor]               NVARCHAR (50) NULL,
    [añoTransaccion]            NVARCHAR (50) NULL,
    [mesTransaccion]            NVARCHAR (50) NULL,
    [lapsoTransaccion]          NVARCHAR (50) NULL,
    [numeroNegocio1]            NVARCHAR (50) NULL,
    [numeroNegocio2DV]          NVARCHAR (50) NULL,
    [numeroNegocio3Endoso]      NVARCHAR (50) NULL,
    [numeroNegocio4PZAAgrupad]  NVARCHAR (50) NULL,
    [identificacionNegocio]     NVARCHAR (50) NULL,
    [planOramo]                 NVARCHAR (50) NULL,
    [periodoFacturaalturaCuota] NVARCHAR (50) NULL,
    [localidadRecaudo]          NVARCHAR (50) NULL,
    [numeroReciboRecaudo]       NVARCHAR (50) NULL,
    [fechaRecaudo]              NVARCHAR (50) NULL,
    [valorRecaudo]              NVARCHAR (50) NULL,
    [codigoConcepto]            NVARCHAR (50) NULL,
    [valorConcepto]             NVARCHAR (50) NULL,
    [porcentajeComision]        NVARCHAR (50) NULL,
    [porcentajeParticipacion]   NVARCHAR (50) NULL,
    [procesoActualiza]          NVARCHAR (50) NULL,
    [usuarioActualiza]          NVARCHAR (50) NULL,
    [fechaActualizacion]        NVARCHAR (50) NULL,
    [horaActualizacion]         NVARCHAR (50) NULL,
    [procesoModifica]           NVARCHAR (50) NULL,
    [usuarioModifica]           NVARCHAR (50) NULL,
    [fechaModificacion]         NVARCHAR (50) NULL,
    [horaModificacion]          NVARCHAR (50) NULL,
    [numeroLote]                NVARCHAR (50) NULL,
    [indicadorPago]             NVARCHAR (50) NULL,
    [nombreTomador]             NVARCHAR (50) NULL,
    [ramo1]                     NVARCHAR (50) NULL,
    [ramo2]                     NVARCHAR (50) NULL
);



