CREATE TABLE [dbo].[PersistenciaVIDADetalle](
	[compania_id] [int] NOT NULL,
	[Compania] [nvarchar](100) NULL,
	[zona_id] [int] NOT NULL,
	[zonaNombre] [nvarchar](100) NULL,
	[localidad_id] [int] NOT NULL,
	[Localidad] [nvarchar](100) NULL,
	[jPadre_id] [int] NULL,
	[Director] [nvarchar](100) NULL,
	[participante_id] [int] NOT NULL,
	[Clave] [nvarchar](250) NULL,
	[Canal_id] [int] NOT NULL,
	[Canal] [nvarchar](100) NULL,
	[nombreParticipante] [nvarchar](201) NULL,
	[porcentajeParticipacion] [float] NULL,
	[lineaNegocio_id] [int] NOT NULL,
	[LineaNegocio] [nvarchar](100) NULL,
	[segmento_id] [int] NULL,
	[Segmento] [nvarchar](100) NULL,
	[ramo_id] [int] NOT NULL,
	[Ramo] [nvarchar](150) NULL,
	[producto_id] [int] NOT NULL,
	[Producto] [nvarchar](150) NOT NULL,
	[plan_id] [int] NOT NULL,
	[Plan] [nvarchar](150) NULL,
	[amparo_id] [int] NULL,
	[Amparo] [nvarchar](150) NULL,
	[Cobertura] [nvarchar](100) NULL,
	[modalidadPago_id] [int] NULL,
	[ModalidadPago] [nvarchar](100) NULL,
	[plazo_id] [int] NOT NULL,
	[plazoNombre] [nvarchar](150) NULL,
	[numeroNegocio] [bigint] NULL,
	[estadoNegocio] [nvarchar](100) NULL,
	[valorAhorro] [float] NULL,
	[valorProteccion] [float] NULL,
	[valorPrimaPensiones] [float] NULL,
	[valorPrimaTotal] [float] NULL,
	[mesCierre] [int] NULL,
	[anioCierre] [int] NULL,
	[fechaExpedicion] [date] NULL,
	[fechaGrabacion] [date] NULL,
	[fechaCancelacion] [date] NULL,
	[cedulaCliente] [nvarchar](250) NULL,
	[nombreCliente] [nvarchar](250) NULL,
	[actividadEconomica_id] [int] NULL,
	[ActividadEconomica] [nvarchar](100) NULL,
	[codigoAgrupador] [nvarchar](100) NULL,
	[grupoEndoso_id] [int] NULL,
	[grupoEndoso] [nvarchar](50) NULL,
	[tipoEndoso_id] [int] NULL,
	[tipoEndoso] [nvarchar](50) NULL,
	[claseEndoso] [int] NULL,
	[estadoReal] [nvarchar](5) NULL
);

