CREATE TABLE [integracion].[Negocio] (
    [id]                         INT            NOT NULL,
    [producto_id]                INT            NULL,
    [localidad_id]               INT            NULL,
    [numeroNegocio]              NVARCHAR (250) NULL,
    [fechaExpedicion]            DATETIME       NULL,
    [segmento_id]                INT            NULL,
    [valorAsegurado]             FLOAT          NULL,
    [lineaNegocio_id]            INT            NULL,
    [compania_id]                INT            NULL,
    [ramo_id]                    INT            NULL,
    [zona_id]                    INT            NULL,
    [participante_id]            INT            NULL,
    [clave]                      NVARCHAR (250) NULL,
    [fechaGrabacion]             DATETIME       NULL,
    [fechaRecaudoInicial]        DATETIME       NULL,
    [numeroSolicitud]            NVARCHAR (250) NULL,
    [cuotasPagadas]              FLOAT          NULL,
    [cuotasVencidas]             FLOAT          NULL,
    [identificacionSuscriptor]   NVARCHAR (250) NULL,
    [nombreSuscriptor]           NVARCHAR (250) NULL,
    [generoSuscriptor]           NVARCHAR (100) NULL,
    [porcentajeParticipacion]    FLOAT          NULL,
    [valorProteccion]            FLOAT          NULL,
    [valorAhorro]                FLOAT          NULL,
    [valorPrimaPensiones]        FLOAT          NULL,
    [valorPrimaTotal]            FLOAT          NULL,
    [estadoNegocio]              NVARCHAR (100) NULL,
    [codigoAgrupador]            NVARCHAR (100) NULL,
    [fechaEmisionMaximoEndoso]   DATETIME       NULL,
    [fechaCancelacion]           DATETIME       NULL,
    [Usuarios]                   INT            NULL,
    [tipoDocumentoSuscriptor_id] INT            NULL,
    [plan_id]                    INT            NULL,
    [mesCierre]                  INT            NULL,
    [anioCierre]                 INT            NULL,
    [ramoDetalle_id]             INT            NULL,
    [productoDetalle_id]         INT            NULL,
    [planDetalle_id]             INT            NULL,
    [amparo_id]                  INT            NULL,
    [modalidadPago_id]           INT            NULL,
    [grupoEndoso_id]             INT            NULL,
    [tipoEndoso_id]              INT            NULL,
	[fechaInicioVigencia]        DATE           NULL,
	[fechaFinVigencia]           DATE           NULL,
	[consecutivoEndosoCore]      INT            NULL,
	[cuotasTotales]              INT            NULL,
	[codigoEmision]              INT            NULL,
	[recompra]                   BIT            NULL,
	[numeroRecompra]             BIGINT         NULL,
	[fechaContrato]              DATE           NULL,
	[tipoNovedad]                INT            NULL,
	[fechaEfecto]                DATE           NULL,
	[formaPago_id]               INT            NULL
);