ALTER TABLE [dbo].[aspnet_Membership]
    ADD CONSTRAINT [PK__aspnet_M__1788CC4D7720AD13] PRIMARY KEY NONCLUSTERED ([UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

