ALTER TABLE [dbo].[aspnet_WebEvent_Events]
    ADD CONSTRAINT [PK__aspnet_W__7944C81043A1090D] PRIMARY KEY CLUSTERED ([EventId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

