ALTER TABLE [dbo].[aspnet_UsersInRoles]
    ADD CONSTRAINT [PK__aspnet_U__AF2760AD6CA31EA0] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

