ALTER TABLE [dbo].[aspnet_Users]
    ADD CONSTRAINT [PK__aspnet_U__1788CC4D6319B466] PRIMARY KEY NONCLUSTERED ([UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

