ALTER TABLE [dbo].[LiquidacionFranquiciaProceso]
    ADD CONSTRAINT [PK_LiquidacionFranquiciaProceso_1] PRIMARY KEY CLUSTERED ([liquidacion_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

