ALTER TABLE [dbo].[BatchLog]
    ADD CONSTRAINT [PK_BatchLog] PRIMARY KEY CLUSTERED ([BatchLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

