ALTER TABLE [dbo].[PackageErrorLog]
    ADD CONSTRAINT [PK_PackageErrorLog] PRIMARY KEY CLUSTERED ([PackageErrorLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

