ALTER TABLE [dbo].[aspnet_Profile]
    ADD CONSTRAINT [PK__aspnet_P__1788CC4C038683F8] PRIMARY KEY CLUSTERED ([UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

