ALTER TABLE [dbo].[aspnet_SchemaVersions]
    ADD CONSTRAINT [PK__aspnet_S__5A1E6BC13FD07829] PRIMARY KEY CLUSTERED ([Feature] ASC, [CompatibleSchemaVersion] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

