/*ALTER TABLE [dbo].[PackageVariableLog]
    ADD CONSTRAINT [PK_PackageVariableLog] PRIMARY KEY CLUSTERED ([PackageVariableLogID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

