/*ALTER TABLE [dbo].[PersistenciadeCAPI]
    ADD CONSTRAINT [PK_PersistenciadeCAPI] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);*/

