ALTER TABLE [dbo].[aspnet_Applications]
    ADD CONSTRAINT [UQ__aspnet_A__309103314E1E9780] UNIQUE NONCLUSTERED ([ApplicationName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

