ALTER TABLE [dbo].[aspnet_Paths]
    ADD CONSTRAINT [PK__aspnet_P__CD67DC5854CB950F] PRIMARY KEY NONCLUSTERED ([PathId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

