ALTER TABLE [dbo].[SSISLog]
    ADD CONSTRAINT [PK_SSISLog] PRIMARY KEY CLUSTERED ([EventID] DESC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

