ALTER TABLE [dbo].[aspnet_Applications]
    ADD CONSTRAINT [UQ__aspnet_A__17477DE44B422AD5] UNIQUE NONCLUSTERED ([LoweredApplicationName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

