ALTER TABLE [dbo].[Package]
    ADD CONSTRAINT [PK_Package] PRIMARY KEY CLUSTERED ([PackageID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

