ALTER TABLE [dbo].[PackageVersion]
    ADD CONSTRAINT [PK_PackageVersion] PRIMARY KEY CLUSTERED ([PackageVersionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

