ALTER TABLE [sig].[RecaudosColquinesSIG]
    ADD CONSTRAINT [PK_RecaudosColquinesSIG] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

