//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI_WS.Entidades
{
    
    [DataContract]
    public partial class ExtractoDetallePremioAsesor : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public Nullable<int> codigoPremio
        {
            get { return _codigoPremio; }
            set
            {
                if (_codigoPremio != value)
                {
                    OnComplexPropertyChanging();
                    _codigoPremio = value;
                    OnPropertyChanged("codigoPremio");
                }
            }
        }
        private Nullable<int> _codigoPremio;
    
        [DataMember]
        public string premio
        {
            get { return _premio; }
            set
            {
                if (_premio != value)
                {
                    OnComplexPropertyChanging();
                    _premio = value;
                    OnPropertyChanged("premio");
                }
            }
        }
        private string _premio;
    
        [DataMember]
        public string gano
        {
            get { return _gano; }
            set
            {
                if (_gano != value)
                {
                    OnComplexPropertyChanging();
                    _gano = value;
                    OnPropertyChanged("gano");
                }
            }
        }
        private string _gano;
    
        [DataMember]
        public string descripcionPremioGanado
        {
            get { return _descripcionPremioGanado; }
            set
            {
                if (_descripcionPremioGanado != value)
                {
                    OnComplexPropertyChanging();
                    _descripcionPremioGanado = value;
                    OnPropertyChanged("descripcionPremioGanado");
                }
            }
        }
        private string _descripcionPremioGanado;
    
        [DataMember]
        public Nullable<System.DateTime> fechaCierrePremio
        {
            get { return _fechaCierrePremio; }
            set
            {
                if (_fechaCierrePremio != value)
                {
                    OnComplexPropertyChanging();
                    _fechaCierrePremio = value;
                    OnPropertyChanged("fechaCierrePremio");
                }
            }
        }
        private Nullable<System.DateTime> _fechaCierrePremio;
    
        [DataMember]
        public string condicion
        {
            get { return _condicion; }
            set
            {
                if (_condicion != value)
                {
                    OnComplexPropertyChanging();
                    _condicion = value;
                    OnPropertyChanged("condicion");
                }
            }
        }
        private string _condicion;
    
        [DataMember]
        public string meta
        {
            get { return _meta; }
            set
            {
                if (_meta != value)
                {
                    OnComplexPropertyChanging();
                    _meta = value;
                    OnPropertyChanged("meta");
                }
            }
        }
        private string _meta;
    
        [DataMember]
        public Nullable<double> ejecutado
        {
            get { return _ejecutado; }
            set
            {
                if (_ejecutado != value)
                {
                    OnComplexPropertyChanging();
                    _ejecutado = value;
                    OnPropertyChanged("ejecutado");
                }
            }
        }
        private Nullable<double> _ejecutado;
    
        [DataMember]
        public Nullable<double> faltante
        {
            get { return _faltante; }
            set
            {
                if (_faltante != value)
                {
                    OnComplexPropertyChanging();
                    _faltante = value;
                    OnPropertyChanged("faltante");
                }
            }
        }
        private Nullable<double> _faltante;

        #endregion
        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, ExtractoDetallePremioAsesor complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.codigoPremio", parentPropertyName), complexObject == null ? null : (object)complexObject.codigoPremio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.premio", parentPropertyName), complexObject == null ? null : (object)complexObject.premio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.gano", parentPropertyName), complexObject == null ? null : (object)complexObject.gano);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.descripcionPremioGanado", parentPropertyName), complexObject == null ? null : (object)complexObject.descripcionPremioGanado);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.fechaCierrePremio", parentPropertyName), complexObject == null ? null : (object)complexObject.fechaCierrePremio);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.condicion", parentPropertyName), complexObject == null ? null : (object)complexObject.condicion);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.meta", parentPropertyName), complexObject == null ? null : (object)complexObject.meta);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.ejecutado", parentPropertyName), complexObject == null ? null : (object)complexObject.ejecutado);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.faltante", parentPropertyName), complexObject == null ? null : (object)complexObject.faltante);
        }

        #endregion
    }
}
