//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI_WS.Entidades
{
    
    [DataContract]
    public partial class PersistenciaCapitalizacionAsesor : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public Nullable<double> minimo
        {
            get { return _minimo; }
            set
            {
                if (_minimo != value)
                {
                    OnComplexPropertyChanging();
                    _minimo = value;
                    OnPropertyChanged("minimo");
                }
            }
        }
        private Nullable<double> _minimo;
    
        [DataMember]
        public string mesAcumulada
        {
            get { return _mesAcumulada; }
            set
            {
                if (_mesAcumulada != value)
                {
                    OnComplexPropertyChanging();
                    _mesAcumulada = value;
                    OnPropertyChanged("mesAcumulada");
                }
            }
        }
        private string _mesAcumulada;
    
        [DataMember]
        public Nullable<double> porcentajePeriodo
        {
            get { return _porcentajePeriodo; }
            set
            {
                if (_porcentajePeriodo != value)
                {
                    OnComplexPropertyChanging();
                    _porcentajePeriodo = value;
                    OnPropertyChanged("porcentajePeriodo");
                }
            }
        }
        private Nullable<double> _porcentajePeriodo;
    
        [DataMember]
        public Nullable<double> colquinesDescontar
        {
            get { return _colquinesDescontar; }
            set
            {
                if (_colquinesDescontar != value)
                {
                    OnComplexPropertyChanging();
                    _colquinesDescontar = value;
                    OnPropertyChanged("colquinesDescontar");
                }
            }
        }
        private Nullable<double> _colquinesDescontar;
    
        [DataMember]
        public string plazo
        {
            get { return _plazo; }
            set
            {
                if (_plazo != value)
                {
                    OnComplexPropertyChanging();
                    _plazo = value;
                    OnPropertyChanged("plazo");
                }
            }
        }
        private string _plazo;
    
        [DataMember]
        public string mesPeriodo
        {
            get { return _mesPeriodo; }
            set
            {
                if (_mesPeriodo != value)
                {
                    OnComplexPropertyChanging();
                    _mesPeriodo = value;
                    OnPropertyChanged("mesPeriodo");
                }
            }
        }
        private string _mesPeriodo;
    
        [DataMember]
        public Nullable<double> acumulada
        {
            get { return _acumulada; }
            set
            {
                if (_acumulada != value)
                {
                    OnComplexPropertyChanging();
                    _acumulada = value;
                    OnPropertyChanged("acumulada");
                }
            }
        }
        private Nullable<double> _acumulada;

        #endregion
        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, PersistenciaCapitalizacionAsesor complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.minimo", parentPropertyName), complexObject == null ? null : (object)complexObject.minimo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.mesAcumulada", parentPropertyName), complexObject == null ? null : (object)complexObject.mesAcumulada);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.porcentajePeriodo", parentPropertyName), complexObject == null ? null : (object)complexObject.porcentajePeriodo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.colquinesDescontar", parentPropertyName), complexObject == null ? null : (object)complexObject.colquinesDescontar);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.plazo", parentPropertyName), complexObject == null ? null : (object)complexObject.plazo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.mesPeriodo", parentPropertyName), complexObject == null ? null : (object)complexObject.mesPeriodo);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.acumulada", parentPropertyName), complexObject == null ? null : (object)complexObject.acumulada);
        }

        #endregion
    }
}
