//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace ColpatriaSAI_WS.Entidades
{
    
    [DataContract]
    public partial class SiniestralidadAutosAsesor : INotifyComplexPropertyChanging, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public Nullable<double> primasDevengar
        {
            get { return _primasDevengar; }
            set
            {
                if (_primasDevengar != value)
                {
                    OnComplexPropertyChanging();
                    _primasDevengar = value;
                    OnPropertyChanged("primasDevengar");
                }
            }
        }
        private Nullable<double> _primasDevengar;
    
        [DataMember]
        public Nullable<double> sinIncurrir
        {
            get { return _sinIncurrir; }
            set
            {
                if (_sinIncurrir != value)
                {
                    OnComplexPropertyChanging();
                    _sinIncurrir = value;
                    OnPropertyChanged("sinIncurrir");
                }
            }
        }
        private Nullable<double> _sinIncurrir;
    
        [DataMember]
        public Nullable<double> porcentajeSinIncurrir
        {
            get { return _porcentajeSinIncurrir; }
            set
            {
                if (_porcentajeSinIncurrir != value)
                {
                    OnComplexPropertyChanging();
                    _porcentajeSinIncurrir = value;
                    OnPropertyChanged("porcentajeSinIncurrir");
                }
            }
        }
        private Nullable<double> _porcentajeSinIncurrir;
    
        [DataMember]
        public Nullable<double> colquinesDescontar
        {
            get { return _colquinesDescontar; }
            set
            {
                if (_colquinesDescontar != value)
                {
                    OnComplexPropertyChanging();
                    _colquinesDescontar = value;
                    OnPropertyChanged("colquinesDescontar");
                }
            }
        }
        private Nullable<double> _colquinesDescontar;
    
        [DataMember]
        public Nullable<int> mes
        {
            get { return _mes; }
            set
            {
                if (_mes != value)
                {
                    OnComplexPropertyChanging();
                    _mes = value;
                    OnPropertyChanged("mes");
                }
            }
        }
        private Nullable<int> _mes;

        #endregion
        #region ChangeTracking
    
        private void OnComplexPropertyChanging()
        {
            if (_complexPropertyChanging != null)
            {
                _complexPropertyChanging(this, new EventArgs());
            }
        }
    
        event EventHandler INotifyComplexPropertyChanging.ComplexPropertyChanging { add { _complexPropertyChanging += value; } remove { _complexPropertyChanging -= value; } }
        private event EventHandler _complexPropertyChanging;
    
        private void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged { add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        public static void RecordComplexOriginalValues(String parentPropertyName, SiniestralidadAutosAsesor complexObject, ObjectChangeTracker changeTracker)
        {
            if (String.IsNullOrEmpty(parentPropertyName))
            {
                throw new ArgumentException("String parameter cannot be null or empty.", "parentPropertyName");
            }
    
            if (changeTracker == null)
            {
                throw new ArgumentNullException("changeTracker");
            }
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.primasDevengar", parentPropertyName), complexObject == null ? null : (object)complexObject.primasDevengar);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.sinIncurrir", parentPropertyName), complexObject == null ? null : (object)complexObject.sinIncurrir);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.porcentajeSinIncurrir", parentPropertyName), complexObject == null ? null : (object)complexObject.porcentajeSinIncurrir);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.colquinesDescontar", parentPropertyName), complexObject == null ? null : (object)complexObject.colquinesDescontar);
            changeTracker.RecordOriginalValue(String.Format(CultureInfo.InvariantCulture, "{0}.mes", parentPropertyName), complexObject == null ? null : (object)complexObject.mes);
        }

        #endregion
    }
}
