//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColpatriaSAI_WS.Servicios.LoggingSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoAplicacion", Namespace="http://schemas.datacontract.org/2004/07/ColpatriaSAI.Negocio.Entidades.Informacio" +
        "n")]
    [System.SerializableAttribute()]
    public partial class InfoAplicacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string direccionIPField;
        
        private string nombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string direccionIP {
            get {
                return this.direccionIPField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionIPField, value) != true)) {
                    this.direccionIPField = value;
                    this.RaisePropertyChanged("direccionIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreUsuarioField, value) != true)) {
                    this.nombreUsuarioField = value;
                    this.RaisePropertyChanged("nombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoggingSvc.ILogging")]
    public interface ILogging {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogging/Auditoria", ReplyAction="http://tempuri.org/ILogging/AuditoriaResponse")]
        bool Auditoria(string mensaje, int prioridad, string modulo, ColpatriaSAI_WS.Servicios.LoggingSvc.InfoAplicacion info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogging/Error", ReplyAction="http://tempuri.org/ILogging/ErrorResponse")]
        bool Error(string mensaje, int prioridad, string modulo, System.Diagnostics.TraceEventType tipoEvento, ColpatriaSAI_WS.Servicios.LoggingSvc.InfoAplicacion info);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoggingChannel : ColpatriaSAI_WS.Servicios.LoggingSvc.ILogging, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoggingClient : System.ServiceModel.ClientBase<ColpatriaSAI_WS.Servicios.LoggingSvc.ILogging>, ColpatriaSAI_WS.Servicios.LoggingSvc.ILogging {
        
        public LoggingClient() {
        }
        
        public LoggingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoggingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoggingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Auditoria(string mensaje, int prioridad, string modulo, ColpatriaSAI_WS.Servicios.LoggingSvc.InfoAplicacion info) {
            return base.Channel.Auditoria(mensaje, prioridad, modulo, info);
        }
        
        public bool Error(string mensaje, int prioridad, string modulo, System.Diagnostics.TraceEventType tipoEvento, ColpatriaSAI_WS.Servicios.LoggingSvc.InfoAplicacion info) {
            return base.Channel.Error(mensaje, prioridad, modulo, tipoEvento, info);
        }
    }
}
